// Regenerates video/fonts-embedded.ts from the committed TTFs.
// Fonts ship inside the bundle as data: URLs — no HTTP fetch at render time,
// because font fetches through the render server proved flaky on 2-core CI
// runners (delayRender timeouts mid-render).
import { readFileSync, writeFileSync } from 'node:fs';

const fonts: Array<[constName: string, file: string]> = [
  ['DEVANAGARI_400', 'public/assets/fonts/NotoSerifDevanagari-Regular.ttf'],
  ['DEVANAGARI_700', 'public/assets/fonts/NotoSerifDevanagari-Bold.ttf'],
  ['LATIN_400', 'public/assets/fonts/NotoSerif-Regular.ttf'],
  ['DISPLAY_400', 'public/assets/fonts/ArchivoBlack-Regular.ttf'],
];

const lines = ['// GENERATED by scripts/embed-fonts.ts — do not edit by hand.', ''];
for (const [name, file] of fonts) {
  const b64 = readFileSync(file).toString('base64');
  lines.push(`export const ${name} = 'data:font/ttf;base64,${b64}';`);
}
writeFileSync('video/fonts-embedded.ts', lines.join('\n') + '\n');
console.log('video/fonts-embedded.ts written');
